module.exports = [
  {
    fullName: "Govind Bhadoriya",
    misCode: "MIS1001",
    email: "govindbhadoriya672@gmail.com",
    phone: "9876543210",
    role: "admin",
    isActive: true,
  },

  {
    fullName: "Raghav",
    misCode: "MIS5001",
    email: "raghavsoni4511@gmail.com",
    phone: "9876543210",
    role: "admin",
    isActive: true,
  },
  {
    fullName: "Rahul Patel",
    misCode: "MIS1002",
    email: "govindbhadoriya668@gmail.com",
    phone: "9876543211",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Priya Shah",
    misCode: "MIS1003",
    email: "priya.shah@paruluniversity.ac.in",
    phone: "9876543212",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Amit Mehta",
    misCode: "MIS1004",
    email: "amit.mehta@paruluniversity.ac.in",
    phone: "9876543213",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Neha Joshi",
    misCode: "MIS1005",
    email: "neha.joshi@paruluniversity.ac.in",
    phone: "9876543214",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Karan Desai",
    misCode: "MIS1006",
    email: "karan.desai@paruluniversity.ac.in",
    phone: "9876543215",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Sneha Trivedi",
    misCode: "MIS1007",
    email: "sneha.trivedi@paruluniversity.ac.in",
    phone: "9876543216",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Rohan Shah",
    misCode: "MIS1008",
    email: "rohan.shah@paruluniversity.ac.in",
    phone: "9876543217",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Pooja Parmar",
    misCode: "MIS1009",
    email: "pooja.parmar@paruluniversity.ac.in",
    phone: "9876543218",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Nikhil Verma",
    misCode: "MIS1010",
    email: "nikhil.verma@paruluniversity.ac.in",
    phone: "9876543219",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Anjali Soni",
    misCode: "MIS1011",
    email: "anjali.soni@paruluniversity.ac.in",
    phone: "9876543220",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Harsh Pandya",
    misCode: "MIS1012",
    email: "harsh.pandya@paruluniversity.ac.in",
    phone: "9876543221",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Komal Dave",
    misCode: "MIS1013",
    email: "komal.dave@paruluniversity.ac.in",
    phone: "9876543222",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Yash Thakkar",
    misCode: "MIS1014",
    email: "yash.thakkar@paruluniversity.ac.in",
    phone: "9876543223",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Krunal Chauhan",
    misCode: "MIS1015",
    email: "krunal.chauhan@paruluniversity.ac.in",
    phone: "9876543224",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Bhavik Patel",
    misCode: "MIS1016",
    email: "bhavik.patel@paruluniversity.ac.in",
    phone: "9876543225",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Nidhi Patel",
    misCode: "MIS1017",
    email: "nidhi.patel@paruluniversity.ac.in",
    phone: "9876543226",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Jinal Shah",
    misCode: "MIS1018",
    email: "jinal.shah@paruluniversity.ac.in",
    phone: "9876543227",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Dhruv Modi",
    misCode: "MIS1019",
    email: "dhruv.modi@paruluniversity.ac.in",
    phone: "9876543228",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Mansi Rana",
    misCode: "MIS1020",
    email: "mansi.rana@paruluniversity.ac.in",
    phone: "9876543229",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Arjun Singh",
    misCode: "MIS1021",
    email: "arjun.singh@paruluniversity.ac.in",
    phone: "9876543230",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Tanya Kapoor",
    misCode: "MIS1022",
    email: "tanya.kapoor@paruluniversity.ac.in",
    phone: "9876543231",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Manav Sharma",
    misCode: "MIS1023",
    email: "manav.sharma@paruluniversity.ac.in",
    phone: "9876543232",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Riya Gupta",
    misCode: "MIS1024",
    email: "riya.gupta@paruluniversity.ac.in",
    phone: "9876543233",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Sahil Jain",
    misCode: "MIS1025",
    email: "sahil.jain@paruluniversity.ac.in",
    phone: "9876543234",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Ishita Mehra",
    misCode: "MIS1026",
    email: "ishita.mehra@paruluniversity.ac.in",
    phone: "9876543235",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Vivek Kulkarni",
    misCode: "MIS1027",
    email: "vivek.kulkarni@paruluniversity.ac.in",
    phone: "9876543236",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Mehul Vyas",
    misCode: "MIS1028",
    email: "mehul.vyas@paruluniversity.ac.in",
    phone: "9876543237",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Palak Shah",
    misCode: "MIS1029",
    email: "palak.shah@paruluniversity.ac.in",
    phone: "9876543238",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Dev Patel",
    misCode: "MIS1030",
    email: "dev.patel@paruluniversity.ac.in",
    phone: "9876543239",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Kishan Solanki",
    misCode: "MIS1031",
    email: "kishan.solanki@paruluniversity.ac.in",
    phone: "9876543240",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Aakash Yadav",
    misCode: "MIS1032",
    email: "aakash.yadav@paruluniversity.ac.in",
    phone: "9876543241",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Riddhi Shah",
    misCode: "MIS1033",
    email: "riddhi.shah@paruluniversity.ac.in",
    phone: "9876543242",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Parth Joshi",
    misCode: "MIS1034",
    email: "parth.joshi@paruluniversity.ac.in",
    phone: "9876543243",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Heena Patel",
    misCode: "MIS1035",
    email: "heena.patel@paruluniversity.ac.in",
    phone: "9876543244",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Nirav Shah",
    misCode: "MIS1036",
    email: "nirav.shah@paruluniversity.ac.in",
    phone: "9876543245",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Bhumi Trivedi",
    misCode: "MIS1037",
    email: "bhumi.trivedi@paruluniversity.ac.in",
    phone: "9876543246",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Jay Bhatt",
    misCode: "MIS1038",
    email: "jay.bhatt@paruluniversity.ac.in",
    phone: "9876543247",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Sonal Patel",
    misCode: "MIS1039",
    email: "sonal.patel@paruluniversity.ac.in",
    phone: "9876543248",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Ankit Mishra",
    misCode: "MIS1040",
    email: "ankit.mishra@paruluniversity.ac.in",
    phone: "9876543249",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Mihir Desai",
    misCode: "MIS1041",
    email: "mihir.desai@paruluniversity.ac.in",
    phone: "9876543250",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Khushi Patel",
    misCode: "MIS1042",
    email: "khushi.patel@paruluniversity.ac.in",
    phone: "9876543251",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Om Barot",
    misCode: "MIS1043",
    email: "om.barot@paruluniversity.ac.in",
    phone: "9876543252",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Ritesh Parmar",
    misCode: "MIS1044",
    email: "ritesh.parmar@paruluniversity.ac.in",
    phone: "9876543253",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Naina Shah",
    misCode: "MIS1045",
    email: "naina.shah@paruluniversity.ac.in",
    phone: "9876543254",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Yogesh Patel",
    misCode: "MIS1046",
    email: "yogesh.patel@paruluniversity.ac.in",
    phone: "9876543255",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Vidhi Mehta",
    misCode: "MIS1047",
    email: "vidhi.mehta@paruluniversity.ac.in",
    phone: "9876543256",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Chirag Shah",
    misCode: "MIS1048",
    email: "chirag.shah@paruluniversity.ac.in",
    phone: "9876543257",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Shreya Trivedi",
    misCode: "MIS1049",
    email: "shreya.trivedi@paruluniversity.ac.in",
    phone: "9876543258",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Mayur Patel",
    misCode: "MIS1050",
    email: "mayur.patel@paruluniversity.ac.in",
    phone: "9876543259",
    role: "subadmin",
    isActive: true,
  },
  {
    fullName: "Krisha Desai",
    misCode: "MIS1051",
    email: "krisha.desai@paruluniversity.ac.in",
    phone: "9876543260",
    role: "subadmin",
    isActive: true,
  },
];