// init/fakeStudents.js
// Schema-clean fake data — ready for direct insertMany(), no cleaning
// step needed. Covers every current field, including the newer ones
// (branch, specialization, joiningDate, state/country/city, parulEmailId,
// education marksheets) that wouldn't exist in the legacy raw import.

module.exports = [
  {
    title: 'Mr',
    firstName: 'Yash',
    middleName: 'Pravin',
    lastName: 'Chavan',
    gender: 'male',
    dob: new Date('2006-05-14'),
    bloodGroup: 'O+',
    category: 'General',
    religion: 'Hinduism',
    caste: 'Maratha',
    state: 'Maharashtra',
    country: 'India',
    city: 'Nashik',
    email: 'yash.chavan24@example.com',
    password: '$2b$10$examplehashonlynotreal000000000000000000000000000010',
    enrollmentNo: '24UG040120',
    abcId: '123456789020',
    parulEmailId: null,
    parulEmailActive: false,
    institute: 'Parul Institute of Engineering & Technology (First Shift)',
    course: 'BTech - Bachelor of Technology',
    program: 'PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)',
    department: 'FET',
    branch: 'CSE',
    specialization: 'AIML',
    joiningDate: new Date('2024-08-01'),
    admissionYear: 2024,
    admissionType: 'Regular',
    admissionQuota: 'General',
    studentStatus: 'active',
    phone: '9876543220',
    whatsapp: '9876543220',
    alternateEmail: 'yash.personal@example.com',
    emergencyContact: { name: 'Pravin Chavan', phone: '9876500111' },
    father: { name: 'Pravin Chavan', phone: '9876500111', email: 'pravin.chavan@example.com' },
    mother: { name: 'Sunita Chavan', phone: '9876500112', email: 'sunita.chavan@example.com' },
    presentAddress: {
      address1: 'Boys Hostel A, Room 210',
      address2: null,
      address3: null,
      city: 'Vadodara',
      district: 'Waghodia',
      state: 'Gujarat',
      country: 'India',
      pincode: '391760',
    },
    permanentAddress: {
      address1: '14 Gangapur Road',
      address2: null,
      address3: null,
      city: 'Nashik',
      district: 'Nashik',
      state: 'Maharashtra',
      country: 'India',
      pincode: '422013',
    },
    education: {
      tenth: { marksheet: 'https://example.com/marksheets/yash-10th.pdf' },
      twelfth: { marksheet: 'https://example.com/marksheets/yash-12th.pdf' },
      diploma: null,
    },
    aadhaarNumber: '456789012350',
    role: 'student',
    isActive: true,
    profileStatus: 'verified',
  },
  {
    title: 'Ms',
    firstName: 'Neha',
    middleName: 'Ashok',
    lastName: 'Iyer',
    gender: 'female',
    dob: new Date('2006-09-02'),
    bloodGroup: 'A+',
    category: 'General',
    religion: 'Hinduism',
    caste: 'Iyer',
    state: 'Tamil Nadu',
    country: 'India',
    city: 'Chennai',
    email: 'neha.iyer24@example.com',
    password: '$2b$10$examplehashonlynotreal000000000000000000000000000011',
    enrollmentNo: '24UG040121',
    abcId: '123456789021',
    parulEmailId: null,
    parulEmailActive: false,
    institute: 'Parul Institute of Engineering & Technology (First Shift)',
    course: 'BTech - Bachelor of Technology',
    program: 'PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)',
    department: 'FET',
    branch: 'CSE',
    specialization: 'AIRO',
    joiningDate: new Date('2024-08-01'),
    admissionYear: 2024,
    admissionType: 'Regular',
    admissionQuota: 'General',
    studentStatus: 'active',
    phone: '9876543221',
    whatsapp: '9876543221',
    alternateEmail: null,
    emergencyContact: { name: 'Ashok Iyer', phone: '9876500113' },
    father: { name: 'Ashok Iyer', phone: '9876500113', email: 'ashok.iyer@example.com' },
    mother: { name: 'Radha Iyer', phone: '9876500114', email: null },
    presentAddress: {
      address1: 'Girls Hostel C, Room 118',
      address2: null,
      address3: null,
      city: 'Vadodara',
      district: 'Waghodia',
      state: 'Gujarat',
      country: 'India',
      pincode: '391760',
    },
    permanentAddress: {
      address1: '22 Besant Nagar',
      address2: null,
      address3: null,
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600090',
    },
    education: {
      tenth: { marksheet: 'https://example.com/marksheets/neha-10th.pdf' },
      twelfth: { marksheet: 'https://example.com/marksheets/neha-12th.pdf' },
      diploma: null,
    },
    aadhaarNumber: '567890123460',
    role: 'student',
    isActive: true,
    profileStatus: 'verified',
  },
  {
    title: 'Mr',
    firstName: 'Farhan',
    middleName: null,
    lastName: 'Sheikh',
    gender: 'male',
    dob: new Date('2005-12-20'),
    bloodGroup: 'B+',
    category: 'OBC',
    religion: 'Islam',
    caste: 'Sheikh',
    state: 'Madhya Pradesh',
    country: 'India',
    city: 'Bhopal',
    email: 'farhan.sheikh24@example.com',
    password: '$2b$10$examplehashonlynotreal000000000000000000000000000012',
    enrollmentNo: '24UG040122',
    abcId: null, // came in through diploma route, generated later
    parulEmailId: null,
    parulEmailActive: false,
    institute: 'Parul Institute of Engineering & Technology (First Shift)',
    course: 'BTech - Bachelor of Technology',
    program: 'PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)',
    department: 'FET',
    branch: 'CSE',
    specialization: 'AIML',
    joiningDate: new Date('2024-08-05'),
    admissionYear: 2024,
    admissionType: 'Lateral Entry',
    admissionQuota: 'Other',
    studentStatus: 'active',
    phone: '9876543222',
    whatsapp: '9876543222',
    alternateEmail: 'farhan.personal@example.com',
    emergencyContact: { name: 'Iqbal Sheikh', phone: '9876500115' },
    father: { name: 'Iqbal Sheikh', phone: '9876500115', email: 'iqbal.sheikh@example.com' },
    mother: { name: 'Nasreen Sheikh', phone: '9876500116', email: 'nasreen.sheikh@example.com' },
    presentAddress: {
      address1: 'Boys Hostel B, Room 402',
      address2: null,
      address3: null,
      city: 'Vadodara',
      district: 'Waghodia',
      state: 'Gujarat',
      country: 'India',
      pincode: '391760',
    },
    permanentAddress: {
      address1: '9 MP Nagar',
      address2: null,
      address3: null,
      city: 'Bhopal',
      district: 'Bhopal',
      state: 'Madhya Pradesh',
      country: 'India',
      pincode: '462011',
    },
    education: {
      tenth: { marksheet: 'https://example.com/marksheets/farhan-10th.pdf' },
      twelfth: { marksheet: 'https://example.com/marksheets/farhan-12th.pdf' },
      diploma: { marksheet: 'https://example.com/marksheets/farhan-diploma.pdf' },
    },
    aadhaarNumber: '678901234570',
    role: 'student',
    isActive: true,
    profileStatus: 'verified',
  },
  {
    title: 'Ms',
    firstName: 'Ritika',
    middleName: 'Anil',
    lastName: 'Bansal',
    gender: 'female',
    dob: new Date('2006-02-11'),
    bloodGroup: 'AB+',
    category: 'General',
    religion: 'Hinduism',
    caste: 'Bansal',
    state: 'Delhi',
    country: 'India',
    city: 'New Delhi',
    email: 'ritika.bansal24@example.com',
    password: '$2b$10$examplehashonlynotreal000000000000000000000000000013',
    enrollmentNo: null, // fresh admission, no enrollment number yet
    abcId: null,
    parulEmailId: null,
    parulEmailActive: false,
    institute: 'Parul Institute of Engineering & Technology (First Shift)',
    course: 'BTech - Bachelor of Technology',
    program: 'PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)',
    department: 'FET',
    branch: 'CSE',
    specialization: null,
    joiningDate: null,
    admissionYear: 2026,
    admissionType: 'Regular',
    admissionQuota: 'General',
    studentStatus: 'active',
    phone: '9876543223',
    whatsapp: '9876543223',
    alternateEmail: null,
    emergencyContact: { name: 'Anil Bansal', phone: '9876500117' },
    father: { name: 'Anil Bansal', phone: '9876500117', email: 'anil.bansal@example.com' },
    mother: { name: 'Kavita Bansal', phone: '9876500118', email: null },
    presentAddress: {
      address1: 'Girls Hostel D, Room 30',
      address2: null,
      address3: null,
      city: 'Vadodara',
      district: 'Waghodia',
      state: 'Gujarat',
      country: 'India',
      pincode: '391760',
    },
    permanentAddress: {
      address1: '5 Rajouri Garden',
      address2: null,
      address3: null,
      city: 'New Delhi',
      district: 'West Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110027',
    },
    education: {
      tenth: { marksheet: 'https://example.com/marksheets/ritika-10th.pdf' },
      twelfth: null, // still awaiting results
      diploma: null,
    },
    aadhaarNumber: null,
    role: 'student',
    isActive: true,
    profileStatus: 'pending', // new admission, awaiting admin verification
  },
  {
  title: 'Mr',
  firstName: 'Govind',
  middleName: '',
  lastName: 'Bhadoriya',
  gender: 'male',
  dob: new Date('2004-10-15'),
  bloodGroup: 'B+',
  category: 'General',
  religion: 'Hinduism',
  caste: 'Rajput',
  state: 'Gujarat',
  country: 'India',
  city: 'Vadodara',

  email: 'govindbhadoriya672@gmail.com',

  password: '$2b$10$examplehashonlynotreal000000000000000000000000000014',

  enrollmentNo: '24UG040999',

  abcId: '123456789999',

  googleId: null,
  parulEmailId: null,
  parulEmailActive: false,

  institute: 'Parul Institute of Engineering & Technology (First Shift)',
  course: 'BTech - Bachelor of Technology',
  program: 'PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)',
  department: 'FET',
  branch: 'CSE',
  specialization: 'AIML',

  joiningDate: new Date('2024-08-01'),

  admissionYear: 2024,
  admissionType: 'Regular',
  admissionQuota: 'General',
  studentStatus: 'active',

  phone: '9876543299',
  whatsapp: '9876543299',
  alternateEmail: 'govind.personal@example.com',

  emergencyContact: {
    name: 'Ramesh Bhadoriya',
    phone: '9876500199',
  },

  father: {
    name: 'Ramesh Bhadoriya',
    phone: '9876500199',
    email: 'ramesh.bhadoriya@example.com',
  },

  mother: {
    name: 'Suman Bhadoriya',
    phone: '9876500200',
    email: 'suman.bhadoriya@example.com',
  },

  presentAddress: {
    address1: 'Boys Hostel A, Room 305',
    address2: null,
    address3: null,
    city: 'Vadodara',
    district: 'Waghodia',
    state: 'Gujarat',
    country: 'India',
    pincode: '391760',
  },

  permanentAddress: {
    address1: '101 Shree Residency',
    address2: null,
    address3: null,
    city: 'Vadodara',
    district: 'Vadodara',
    state: 'Gujarat',
    country: 'India',
    pincode: '390019',
  },

  education: {
    tenth: {
      marksheet: 'https://example.com/marksheets/govind-10th.pdf',
    },
    twelfth: {
      marksheet: 'https://example.com/marksheets/govind-12th.pdf',
    },
    diploma: null,
  },

  aadhaarNumber: '789012345678',

  role: 'student',
  isActive: true,
  profileStatus: 'verified',
},
];