// init/data.js
// Raw student data exactly as exported/collected.
// Left untouched here on purpose — all cleaning/conversion happens
// in index.js right before insert, so this file stays a faithful
// copy of the source data if you need to re-check it later.

module.exports = [
  {
    "_id": null,
    "title": "Mr",
    "firstName": "ALUGONDA",
    "middleName": "SAI CHARAN",
    "lastName": "REDDY",
    "fullName": "ALUGONDA SAI CHARAN REDDY",
    "gender": "Male",
    "dob": "14-07-2006",
    "bloodGroup": "O+",
    "category": "OPEN",
    "religion": "HINDU",
    "caste": "Reddy",
    "email": "alugondasaicharanreddy2006@gmail.com",
    "password": null,
    "enrollmentNo": "ALUGONDA",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "South V Below 60",
    "studentStatus": "Active",
    "phone": 9346790218.0,
    "whatsapp": 9346790218.0,
    "alternateEmail": "alugondasaicharanreddy@gmail.com",
    "emergencyContact": {
      "name": "ALUGONDA BAL REDDY",
      "phone": 9912633443.0
    },
    "father": {
      "name": "ALUGONDA BAL REDDY",
      "phone": 9912592323.0,
      "email": "alugondabalreddy1977@gmail.com"
    },
    "mother": {
      "name": "A.PADMA",
      "phone": 9912633443.0,
      "email": "alugondapadma1984@gmail.com"
    },
    "presentAddress": {
      "address1": "SARDAR bhavan A",
      "address2": "WHAGHODIA TALUKA ",
      "address3": "LIMBDA",
      "city": "VADODARA",
      "district": "VADODARA",
      "state": "GUJARAT",
      "country": "INDIA",
      "pincode": 391760.0
    },
    "permanentAddress": {
      "address1": "201, kachams residency, Godavari homes ",
      "address2": "Suchitra ",
      "address3": "Telangana 500055",
      "city": "Hyderabad",
      "district": "Medchal malkajgiri ",
      "state": "Telangana",
      "country": "India",
      "pincode": 500055.0
    },
    "aadhaarNumber": 591790567612.0,
    "mentorFaculty": "SUNNY RAMCHANDANI",
    "role": "student",
    "isActive": true,
    "profileStatus": null,
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "A SUDARSHAN",
    "middleName": "VENKATESWARLU",
    "lastName": "A",
    "fullName": "A SUDARSHAN VENKATESWARLU A",
    "gender": "Male",
    "dob": "29-01-2007",
    "bloodGroup": "O+",
    "category": "OPEN",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "advikbansal1812@gmail.com",
    "password": null,
    "enrollmentNo": "24UG034665",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "South V 70",
    "studentStatus": "Active",
    "phone": 8310326585.0,
    "whatsapp": 8310326585.0,
    "alternateEmail": null,
    "emergencyContact": {
      "name": 7026732615.0,
      "phone": 9916905888.0
    },
    "father": {
      "name": "ANEGONDI VENKATESWARLU",
      "phone": 9916905888.0,
      "email": "tataprateek1@gmail.com"
    },
    "mother": {
      "name": "ANEGONDI PADMAVATHI",
      "phone": 7026732615.0,
      "email": "shikhajindal13@gmail.com"
    },
    "presentAddress": {
      "address1": "A-7, Omkar Society 1, In front of Saket Apartment ,gali adjacent to shiv clinic,sayajipura,vadodara",
      "address2": "A-7, Omkar Society 1, In front of Saket Apartment ,gali adjacent to shiv clinic,sayajipura,vadodara",
      "address3": "A-7, Omkar Society 1, In front of Saket Apartment ,gali adjacent to shiv clinic,sayajipura,vadodara",
      "city": "Vadodara ",
      "district": "Vadodara ",
      "state": "Gujarat ",
      "country": "india",
      "pincode": 390019.0
    },
    "permanentAddress": {
      "address1": "82,arya nagar, sardhana road,meerut cantt",
      "address2": "82,arya nagar, sardhana road,meerut cantt",
      "address3": "82,arya nagar, sardhana road,meerut cantt",
      "city": "meerut",
      "district": "meerut",
      "state": "up",
      "country": "India",
      "pincode": 250001.0
    },
    "aadhaarNumber": 245901612070.0,
    "mentorFaculty": "Mr.Alok Singh Kushwaha",
    "role": "student",
    "isActive": true,
    "profileStatus": null,
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Miss",
    "firstName": "AARUSHI SHARMA",
    "middleName": "Praveen",
    "lastName": "SHARMA",
    "fullName": "AARUSHI SHARMA Praveen SHARMA",
    "gender": "Female",
    "dob": "29-10-2006",
    "bloodGroup": "B+",
    "category": "OPEN",
    "religion": "Hinduism",
    "caste": "HINDU BRAHMAN",
    "email": "aarushisharma432@gmail.com",
    "password": null,
    "enrollmentNo": "24UG035224",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "VACANT QUOTA",
    "studentStatus": "Active",
    "phone": 7464854639.0,
    "whatsapp": 7464854639.0,
    "alternateEmail": "aarushisharma432@gmail.com",
    "emergencyContact": {
      "name": "Kanchan Sharma ",
      "phone": 6351264631.0
    },
    "father": {
      "name": "PRAVEEN SHARMA",
      "phone": 7016271580.0,
      "email": null
    },
    "mother": {
      "name": "KANCHAN SHARMA",
      "phone": 6351264631.0,
      "email": null
    },
    "presentAddress": {
      "address1": "403, B block ",
      "address2": "Amazon recidency, pancham villa, ",
      "address3": "kamla Nagar",
      "city": "Vadodara ",
      "district": "Vadodara district,",
      "state": "Gujarat ",
      "country": "India",
      "pincode": 390019.0
    },
    "permanentAddress": {
      "address1": "Lakhera building, opp inderlok hotel, ",
      "address2": "devi road, kotdwar,",
      "address3": ".. uttrakhand ",
      "city": "Kotdwar uttrakhand ",
      "district": "Pauri Garhwal ",
      "state": "Uttrakhand ",
      "country": "India ",
      "pincode": 246149.0
    },
    "aadhaarNumber": 843626933186.0,
    "mentorFaculty": "SUNNY RAMCHANDANI",
    "role": "student",
    "isActive": true,
    "profileStatus": null,
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "AAYUSH S KUSHWAHA",
    "middleName": "SANJAY",
    "lastName": "KUSHWAHA",
    "fullName": "AAYUSH S KUSHWAHA SANJAY KUSHWAHA",
    "gender": "Male",
    "dob": "15-02-2005",
    "bloodGroup": "B+",
    "category": "OBC (SEBC)",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "aayushkus15@gmail.com",
    "password": null,
    "enrollmentNo": "24UG032362",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "VACANT QUOTA",
    "studentStatus": "Active",
    "phone": 9471448424.0,
    "whatsapp": 9471448424.0,
    "alternateEmail": "15aayush18@gmail.com",
    "emergencyContact": {
      "name": null,
      "phone": 6207995932.0
    },
    "father": {
      "name": "Sanjay Kushwaha",
      "phone": 6207995932.0,
      "email": "Voptplus@gmail.com "
    },
    "mother": {
      "name": "Mamta devi",
      "phone": 7903972853.0,
      "email": "15aayush18@gmail.com"
    },
    "presentAddress": {
      "address1": "Atal Bhawan , Room no.-308",
      "address2": null,
      "address3": null,
      "city": "Vadodara ",
      "district": "Vadodara ",
      "state": "Gujarat ",
      "country": "India",
      "pincode": 391760.0
    },
    "permanentAddress": {
      "address1": "Nawada khurd",
      "address2": null,
      "address3": null,
      "city": "Hajipur",
      "district": "Vaishali",
      "state": "Bihar",
      "country": "India",
      "pincode": 844102.0
    },
    "aadhaarNumber": 468483331118.0,
    "mentorFaculty": "Shaikh Mohd Maaz",
    "role": "student",
    "isActive": true,
    "profileStatus": null,
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "AAYUSH THAKRE",
    "middleName": "VINOD",
    "lastName": "THAKRE",
    "fullName": "AAYUSH THAKRE VINOD THAKRE",
    "gender": "Male",
    "dob": "2005-11-09T00:00:00",
    "bloodGroup": "O+",
    "category": "OBC (SEBC)",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "aayushthakre487@gmail.com",
    "password": null,
    "enrollmentNo": "24UG034121",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "VACANT QUOTA",
    "studentStatus": "Active",
    "phone": "+91 6265604881",
    "whatsapp": "+91 6265604881",
    "alternateEmail": null,
    "emergencyContact": {
      "name": null,
      "phone": "+91 6261912478"
    },
    "father": {
      "name": "VINOD THAKRE",
      "phone": "+91 6261912478",
      "email": null
    },
    "mother": {
      "name": "CHANDRAKALA THAKRE",
      "phone": "+91 9754438864",
      "email": null
    },
    "presentAddress": {
      "address1": "A/22, Kotyark Nagar Society, Pani Gate",
      "address2": null,
      "address3": null,
      "city": "Vadodara",
      "district": "Vadodara",
      "state": "Gujarat",
      "country": "India",
      "pincode": 390017.0
    },
    "permanentAddress": {
      "address1": "Koste",
      "address2": null,
      "address3": null,
      "city": "Balaghat",
      "district": "Balaghat",
      "state": "Madhya Pradesh",
      "country": "India",
      "pincode": 481331.0
    },
    "aadhaarNumber": 7297874902.0,
    "mentorFaculty": "Deepika Pandey",
    "role": "student",
    "isActive": true,
    "profileStatus": "yes",
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "ABHAY DWIVEDI",
    "middleName": null,
    "lastName": "DWIVEDI",
    "fullName": "ABHAY DWIVEDI DWIVEDI",
    "gender": "Male",
    "dob": "2007-07-07T00:00:00",
    "bloodGroup": null,
    "category": "OPEN",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "abhay.967863@gmail.com",
    "password": null,
    "enrollmentNo": "24UG036450",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "VACANT QUOTA",
    "studentStatus": "Active",
    "phone": 6393157525.0,
    "whatsapp": 6393157525.0,
    "alternateEmail": "vk6982183@gmail.com",
    "emergencyContact": {
      "name": null,
      "phone": 6393157525.0
    },
    "father": {
      "name": "PAWAN DWIVEDI",
      "phone": 7800189794.0,
      "email": "abhay.967863@gmail.com"
    },
    "mother": {
      "name": "ANITA DWIVEDI",
      "phone": 7800189794.0,
      "email": null
    },
    "presentAddress": {
      "address1": "Atal bhawan B",
      "address2": "parul university",
      "address3": "waghodia",
      "city": "vadodara",
      "district": "Waghodia ",
      "state": "Gujarat ",
      "country": "India ",
      "pincode": 391760.0
    },
    "permanentAddress": {
      "address1": "Tighra -Sant Kabir Nagar, Uttar Pradesh ",
      "address2": "Tighra Sant kabir Nagar Uttar Pradesh ",
      "address3": "Tighra sant kabir nagar uttar pradesh ",
      "city": "Khalilabad",
      "district": "Sant kabir Nagar (SKN)",
      "state": "Uttar Pradesh ",
      "country": "India ",
      "pincode": 272199.0
    },
    "aadhaarNumber": 890962210134.0,
    "mentorFaculty": "ARUNESH P SINGH",
    "role": "student",
    "isActive": true,
    "profileStatus": "yes",
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "ABHISHEK BALAPPA KARALINGANNAVAR",
    "middleName": null,
    "lastName": "KARALINGANNAVAR",
    "fullName": "ABHISHEK BALAPPA KARALINGANNAVAR KARALINGANNAVAR",
    "gender": "Male",
    "dob": "18-11-2006",
    "bloodGroup": "A+",
    "category": "OBC (SEBC)",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "abhishekk05786@gmail.com",
    "password": null,
    "enrollmentNo": "24UG035941",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "South V 90",
    "studentStatus": "Active",
    "phone": 6361157580.0,
    "whatsapp": 6361157580.0,
    "alternateEmail": "abhishekk05786@gmail.com",
    "emergencyContact": {
      "name": 9591850831.0,
      "phone": 8971258965.0
    },
    "father": {
      "name": "BALAPPA S KARALINGANNAVAR",
      "phone": 9591850831.0,
      "email": "abhishekk05786@gmail.com"
    },
    "mother": {
      "name": "MAHANANDA KARALINGANNAVAR",
      "phone": 8971258965.0,
      "email": "abhishekk05786@gmail.com"
    },
    "presentAddress": {
      "address1": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi ",
      "address2": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi ",
      "address3": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi",
      "city": "Belagavi ",
      "district": "Belagavi ",
      "state": "Karnataka ",
      "country": "India",
      "pincode": 590016.0
    },
    "permanentAddress": {
      "address1": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi ",
      "address2": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi",
      "address3": "Ramthirth nagar , k a b last second stop ploat no 3716 distict Belagavi",
      "city": "Belagavi ",
      "district": "Belagavi ",
      "state": "Karnataka ",
      "country": "India",
      "pincode": 590016.0
    },
    "aadhaarNumber": 829138369651.0,
    "mentorFaculty": "ARUNESH P SINGH",
    "role": "student",
    "isActive": true,
    "profileStatus": "yes",
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "ACHAMPETA VAMSHIKRISHNA",
    "middleName": null,
    "lastName": "ACHAMPETA",
    "fullName": "ACHAMPETA VAMSHIKRISHNA ACHAMPETA",
    "gender": "Male",
    "dob": "25-10-2005",
    "bloodGroup": null,
    "category": "OPEN",
    "religion": "HINDU",
    "caste": null,
    "email": "vamshiachampeta@gmail.com",
    "password": null,
    "enrollmentNo": "24UG036149",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "South V 70",
    "studentStatus": "Active",
    "phone": 7093276859.0,
    "whatsapp": 7093276859.0,
    "alternateEmail": "vamshiachampeta@gmail.com",
    "emergencyContact": {
      "name": null,
      "phone": 7093276869.0
    },
    "father": {
      "name": "ACHAMPETA SWAMY",
      "phone": 9948294259.0,
      "email": "swamyachampet343@gmail.com"
    },
    "mother": {
      "name": "ACHAMPETA PADHMA",
      "phone": 9866529434.0,
      "email": "padmaachampet851@gmail.com"
    },
    "presentAddress": {
      "address1": "Chandaipet",
      "address2": null,
      "address3": null,
      "city": "Chegunta",
      "district": "Medak",
      "state": "Telangana",
      "country": "India",
      "pincode": 502247.0
    },
    "permanentAddress": {
      "address1": "Chandaipet",
      "address2": null,
      "address3": null,
      "city": "Chegunta",
      "district": "Medak",
      "state": "Telangana",
      "country": "India",
      "pincode": 502247.0
    },
    "aadhaarNumber": "8607 9451 5311",
    "mentorFaculty": "Deepika Pandey",
    "role": "student",
    "isActive": true,
    "profileStatus": null,
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Mr",
    "firstName": "ADAPA VAMSI SURYA MANIKANTA",
    "middleName": null,
    "lastName": "ADAPA",
    "fullName": "ADAPA VAMSI SURYA MANIKANTA ADAPA",
    "gender": "Male",
    "dob": "30-04-2006",
    "bloodGroup": "O+",
    "category": "OPEN",
    "religion": "Hinduism",
    "caste": "HINDU",
    "email": "vamsiadapa74@gmail.com",
    "password": null,
    "enrollmentNo": "24UG030820",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "South V 90",
    "studentStatus": "Active",
    "phone": 9701310239.0,
    "whatsapp": 9701310239.0,
    "alternateEmail": "vamsiadapa74@gmail.com",
    "emergencyContact": {
      "name": null,
      "phone": 9701310239.0
    },
    "father": {
      "name": "ADAPA VEERA VENKATA SATYA NARAYANA",
      "phone": 9676263936.0,
      "email": "vaanipadmasupriya2004@gmail.com"
    },
    "mother": {
      "name": "ADAPA VENKATA LAKSHMI",
      "phone": 9441846936.0,
      "email": "venkatalakshmiadapa323@gmail.com"
    },
    "presentAddress": {
      "address1": "Atal A1 ",
      "address2": "parul university",
      "address3": null,
      "city": "Vadodara ",
      "district": "Vadodara ",
      "state": "Gujarat ",
      "country": "INDIA",
      "pincode": 391760.0
    },
    "permanentAddress": {
      "address1": "AKRAM GUEST HOUSE SAMISRAGUDAM ",
      "address2": "Rajamundry ",
      "address3": "Andhra Pradesh ",
      "city": "Nidadavolu ",
      "district": "Rajamundry ",
      "state": "Andhra Pradesh ",
      "country": "Indian ",
      "pincode": 534301.0
    },
    "aadhaarNumber": 394142562253.0,
    "mentorFaculty": "kamini sharma",
    "role": "student",
    "isActive": true,
    "profileStatus": "yes",
    "createdAt": null,
    "updatedAt": null
  },
  {
    "_id": null,
    "title": "Miss",
    "firstName": "ADITI GUPTA",
    "middleName": null,
    "lastName": "GUPTA",
    "fullName": "ADITI GUPTA GUPTA",
    "gender": "Female",
    "dob": "25-03-2006",
    "bloodGroup": "B+",
    "category": "OPEN",
    "religion": "Hinduism",
    "caste": "BANIYA",
    "email": "ananyaditi32@gmail.com",
    "password": null,
    "enrollmentNo": "24UG036412",
    "institute": "Parul Institute of Engineering & Technology (First Shift)",
    "course": "BTech - Bachelor of Technology",
    "program": "PIET-1 - BTech - Computer Science & Engineering(Artificial Intelligence & Machine Learning)",
    "department": null,
    "admissionYear": 2024.0,
    "admissionType": "Regular",
    "admissionQuota": "MANAGEMENT QUOTA",
    "studentStatus": "Active",
    "phone": 8787240653.0,
    "whatsapp": 8787240653.0,
    "alternateEmail": "ananyaditi32@gmail.com",
    "emergencyContact": {
      "name": 8787240653.0,
      "phone": null
    },
    "father": {
      "name": "Avnish Gupta",
      "phone": 8423145002.0,
      "email": "ananyaditi32@gmail.com"
    },
    "mother": {
      "name": "Deepti Rawat",
      "phone": 8423145002.0,
      "email": "ananyaditi32@gmail.com"
    },
    "presentAddress": {
      "address1": "Shakuntala hostel b",
      "address2": null,
      "address3": null,
      "city": "Vadodara",
      "district": "Waghodia",
      "state": "Gujarat",
      "country": "India",
      "pincode": 391760.0
    },
    "permanentAddress": {
      "address1": "New patel nagar,orai",
      "address2": null,
      "address3": null,
      "city": "Orai",
      "district": "Jalaun",
      "state": "Uttar pradesh",
      "country": "India",
      "pincode": 285001.0
    },
    "aadhaarNumber": 413601000000.0,
    "mentorFaculty": "Deepika Pandey",
    "role": "student",
    "isActive": true,
    "profileStatus": "yes",
    "createdAt": null,
    "updatedAt": null
  }
];